### ISSUE TITLE
Extension not compatible with PHP 7.0

### ISSUE THREAD

**Issue by zebastiane** [FluidTYPO3/fluidcontent_core#211]
I have installed a new TYPO3 CMS LTS (7.6.1) environment with PHP 7.0 and
* `fluidcontent_core` 1.4.0
* `flux` 7.3.0

Unfortunately I get this exception when creating a new page for example (drag&drop in tree or with list module).

> PHP Warning: Declaration of FluidTYPO3\FluidcontentCore\Provider\CoreContentProvider::injectConfigurationService(FluidTYPO3\FluidcontentCore\Service\ConfigurationService $configurationService) should be compatible with FluidTYPO3\Flux\Provider\AbstractProvider::injectConfigurationService(FluidTYPO3\Flux\Service\FluxService $configurationService) in /var/www/html/htdocs/www/typo3conf/ext/fluidcontent_core/Classes/Provider/CoreContentProvider.php line 29

`fluidcontent_core` is not [listed with the compatible TYPO3 LTS extensions](https://fluidtypo3.org/blog/news/lts-compatible-versions-released.html), but is compatible with [TYPO3 CMS 7.6.0-7.6.99](http://typo3.org/extensions/repository/view/fluidcontent_core).

No exception with PHP 5.6.

**Comment by kersten** [comment]
got the same error here.

**Comment by xf-** [comment]
Hi,

the problem with PHP7 is argument types in overwritten/extended functions.

Example based on fluidpages (same issue):
```
Flux AbstractProvider has:
	/**
	 * @param FluxService $configurationService
	 * @return void
	 */
	public function injectConfigurationService(FluxService $configurationService) {
		$this->configurationService = $configurationService;
	}
```
```
Fluidpages PageProvider extends AbstractProvider
	/**
	 * @param ConfigurationService $configurationService
	 * @return void
	 */
	public function injectConfigurationService(ConfigurationService $configurationService) {
		$this->configurationService = $configurationService;
	}
```
ConfigurationService extends from FluxService

We need a separate injection and variable.
Patches are welcome.

xaver

**Comment by xf-** [comment]
https://github.com/FluidTYPO3/flux/pull/1048 should solve it

**Comment by wazum** [comment]
I still get this error with TYPO3 7.6, PHP 7.0.11 and the latest version of all extensions (flux, fluidcontent_core). What needs to be done to fix this?

**Comment by NamelessCoder** [comment]
@wazum Use `dev-development` branches until further notice - and see https://fluidtypo3.org/blog/news/preparing-flux-750.html for a bit of explanation.
